config/routes.rb
Rails.application.routes.draw do
  get 'accounts/index'

  root 'accounts#index'

  resources :accounts do
    resources :transactions 
  end

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :transactions, dependent: :destroy
  validates :name, presence: true

  
   def update_balance!
    debit = self.transactions.where(transaction_type: "debit").sum(:amount)
    credit = self.transactions.where(transaction_type: "credit").sum(:amount)
    
    update_attributes(
      balance: debit - credit
      )
    # self.balance = self.account_entries.sum(:amount)
  end
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :account
  validates :description, presence: true
  validates :amount, presence: true
  validates :transaction_type, presence: true
  after_save :update_account_balance!
  after_destroy :update_account_balance!

  scope :debit, -> { where(transaction_type: "debit") }
  scope :credit, -> { where(transaction_type: "credit") }
  scope :fixed, -> { where(fixed_transaction: true) } 
  scope :variable, -> { where(fixed_transaction: false ) }


  #through associations
  def update_account_balance!
    account.update_balance!
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    @accounts = Account.all
  end

  def show
    @account = Account.find(params[:id])
    @transactions = @account.transactions
  end

  def create
    @account = Account.create(account_params)
    if @account.save
      flash[:sucess] = t(:account_create_success)
      redirect_to accounts_path
    else
      flash[:error] = t(:account_create_error)
      render :new
    end
  end

  def destroy
    if Account.find(params[:id]).destroy
      redirect_to accounts_path
    end
  end

  def new
    @account = Account.new
  end

  private
  def account_params
    params.require(:account).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  before_action :find_account, except: [:destroy]

  def new
     @transaction = @account.transactions.build
  end

  def show
    @transaction = @account.transactions.find(params[:id])
  end

   def create
    @transaction = @account.transactions.build(transaction_params)
    if @transaction.save
       flash[:success] = "saved"    
       redirect_to @account
     else
       flash[:error] = "not saved"
       render :new
     end
   end

   def edit
    @transaction = @account.transactions.find(params[:id])
   end
   
   def update
    @transaction = @account.transactions.find(params[:id])

    if @transaction.update_attributes(transaction_params)
      flash[:success] = "vertaling hier"
      redirect_to @account
    else
      flash[:error] = "vertaling hier"
      render :edit
    end
   end

  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy
    redirect_to account_path(@transaction.account)
  end


  private

    def find_account
      @account = Account.find(params[:account_id])
      # for nested transaction resource
    end

    def transaction_params
      params.require(:transaction).permit(:description, :amount, :transaction_type, :fixed_transaction)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/accounts/_transaction_fields.html.haml
%td= link_to transaction.description, account_transaction_path(transaction.account, transaction)
%td= transaction.amount
%td= transaction.transaction_type
/ %strong= t('transactions_fixed')
/ %span= t.fixed_transaction
-#%td= link_to "edit", edit_account_transaction_path(transaction.account, transaction)
-#%td= link_to "delete", account_transaction_path(transaction.account, transaction), method: :delete, data: { confirm: "Weet je het zeker?" } 

app/views/accounts/index.html.haml
%h1= t("accounts_index_heading")

= link_to t("accounts_index_new"), new_account_path, class: "btn btn-primary"

- @accounts.each do |account|
  %p
    = link_to account.name, account
    = link_to "delete", account, method: :delete, data: { confirm: "weet je het zeker?"}

app/views/accounts/new.html.haml
%h1= t('accounts_new_heading')

= simple_form_for(@account, html: { novalidate: true}) do |f|
  = f.input :name
  = f.submit

app/views/accounts/show.html.haml
%h1= t('accounts_show_heading')

%h2= @account.name
= link_to t('accounts_show_new'), new_account_transaction_path(@account), class: 'btn btn-primary'

%table
  %th= t('transactions_fixed')
  %th= t('transactions_amount')
  %th= t('transactions_type')
  - @transactions.debit.fixed.each do |t|
    %tr.highlight__debit
      = render 'transaction_fields', transaction: t 
   
  - @transactions.credit.fixed.each do |t|
    %tr.highlight__credit 
      = render 'transaction_fields', transaction: t

%table
  %th= t('transactions_variable')
  %th= t('transactions_amount')
  %th= t('transactions_type')
  - @transactions.debit.variable.each do |t|
    %tr.highlight__debit 
      = render 'transaction_fields', transaction: t

  - @transactions.credit.variable.each do |t|
    %tr.highlight__credit
      = render 'transaction_fields', transaction: t
  %tr.highlight__balance
    %th= t('accounts_show_balance')
    %th= @account.balance

%h3= link_to t('accounts_show_back'), accounts_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => 'robots', :content => 'noindex'}
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{:name => 'viewport', :content => 'width=device-width, initial-scale=1.0'}
    %title MoneyApp
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .wrapper
      = yield
      = debug(params) if Rails.env.development?

app/views/transactions/edit.html.haml
%h1= t(:transactions_new_title)

= simple_form_for [@account, @transaction] do |f|
  = f.input :transaction_type, collection: ["debit", "credit"]
  = f.input :description
  = f.input :amount
  = f.input :fixed_transaction
  = f.submit

app/views/transactions/new.html.haml
%h1= t('transactions_new_heading')

= simple_form_for [@account, @transaction] do |f|
  = f.input :transaction_type, collection: ["debit", "credit"]
  = f.input :description
  = f.input :amount
  = f.input :fixed_transaction
  = f.submit

app/views/transactions/show.html.haml
%ul
  %li= @transaction.description
  %li= @transaction.amount
  %li= @transaction.transaction_type
  %li= link_to "edit", edit_account_transaction_path(@transaction.account, @transaction)
  %td= link_to "delete", account_transaction_path(@transaction.account, @transaction), method: :delete, data: { confirm: "Weet je het zeker?" } 